### ISSUE TITLE
rustflags in cargo config?

### ISSUE THREAD

**Issue by wezm** [amacd31/bit-counter#1]
I wonder if it would be worth putting something like the following in `.cargo/config.toml`:

```toml
[build]
rustflags = ["-C", "target-feature=+popcnt"] 
```

That way builds would automatically use of popcnt by default and you could simplify the documentation and CI a bit. If you did go down this path you could add a note about the inverse: If someone wants to build for a CPU that doesn't support popcnt then they should build with `RUSTFLAGS="-C target-feature=-popcnt"`
